### PR TITLE
 Moved the nginx-full formula from Ensembl/homebrew-nginx 

### PR DESCRIPTION
**Pull request by muffato**
I couldn't see if Ensembl/homebrew-nginx is actually used anywhere (also checked the Docker images from @andrewyatz or @nicklangridge ). homebrew-external is a better place to host this file

### CODE REVIEW

**Comment by muffato** [comment]
Hum, just found about Ensembl/homebrew-web which has its own version of `nginx-full.rb`. I don't know which one is correct

**Comment by andrewyatz** [comment]
Just asking @ens-ds23 about this. It's better he says which one is in use

**Comment by thomasmaurel** [comment]
@ens-ds23: Did you had time to look into this?

**Comment by ens-ds23** [comment]
Here's what we do:

brew install ensembl/web/nginx-full --with-set-misc-module

from

https://github.com/Ensembl/homebrew-web/blob/master/nginx-full.rb

I can change if necessary as we're doing a rebuild right now. Sorry for missing this: it got lost in a deluge of git notifications.

**Comment by muffato** [comment]
I think I would close this PR, then.
@ens-ds23 : when I made this PR, I was not aware of `homebrew-web`. Looking at this repo now, it looks like you have many things there and that's what you use and maintain. I don't think there is a compelling reason to make the move

**Pull request closed without merging**
